"""HomePASS domain models."""

from .access_device import (
    AccessDevice,
    AccessDeviceData,
    AccessDeviceIntegration,
    AccessDeviceKind,
    AccessDeviceSetupState,
    KeypadOperation,
    default_keypad_button_actions,
)
from .access_grant import AccessGrant, AccessGrantData
from .access_metadata import (
    AccessDriver,
    AccessMetadata,
    AccessMetadataData,
)
from .access_point import AccessPoint, AccessPointData
from .activity import (
    ACTIVITY_EVENT_DEFINITIONS,
    ActivityAccessMethod,
    ActivityActorType,
    ActivityAttributeValue,
    ActivityCategory,
    ActivityEvent,
    ActivityEventData,
    ActivityEventDefinition,
    ActivityEventType,
    ActivityNavigationKind,
    ActivityNavigationReference,
    ActivityOutcome,
    ActivitySeverity,
    ActivitySource,
    LockEventOrigin,
    activity_event_definition,
)
from .authorization import AuthorizationDecision, authorize_access
from .lifecycle_operation import (
    LifecycleOperation,
    LifecycleOperationData,
    LifecycleOperationStatus,
    LifecyclePayloadValue,
)
from .notification import (
    CATEGORY_TITLES,
    NOTIFICATION_DEFINITIONS,
    NotificationCategory,
    NotificationDefinition,
    NotificationEvent,
    notification_event_for_activity,
)
from .notification_preferences import NotificationPreferences
from .person import Person, PersonData
from .property_settings import (
    MAX_PROPERTY_NAME_LENGTH,
    PROPERTY_SETTINGS_SCHEMA_VERSION,
    PropertySettings,
    PropertySettingsValidationError,
    normalize_property_name,
)
from .schedule import (
    PERMANENT_SCHEDULE_ID,
    PERMANENT_SCHEDULE_NAME,
    DayOfWeek,
    Schedule,
    ScheduleData,
    WeeklyRule,
    WeeklyRuleData,
    permanent_schedule,
)
from .schedule_evaluation import ScheduleEvaluation, evaluate_schedule
from .synchronization import (
    AccessPointSynchronization,
    AccessPointSynchronizationData,
    SynchronizationStatus,
    aggregate_synchronization_status,
)
from .synchronization_history import (
    SynchronizationHistoryEvent,
    SynchronizationHistoryEventData,
    SynchronizationHistoryEventType,
    SynchronizationHistorySeverity,
)

__all__ = [
    "AccessDevice",
    "AccessDeviceData",
    "AccessDeviceIntegration",
    "AccessDeviceKind",
    "AccessDeviceSetupState",
    "AccessGrant",
    "AccessGrantData",
    "AccessDriver",
    "AccessMetadata",
    "AccessMetadataData",
    "AccessPoint",
    "AccessPointData",
    "AccessPointSynchronization",
    "AccessPointSynchronizationData",
    "AuthorizationDecision",
    "ACTIVITY_EVENT_DEFINITIONS",
    "ActivityAccessMethod",
    "ActivityActorType",
    "ActivityAttributeValue",
    "ActivityCategory",
    "ActivityEvent",
    "ActivityEventData",
    "ActivityEventDefinition",
    "ActivityEventType",
    "ActivityNavigationKind",
    "ActivityNavigationReference",
    "ActivityOutcome",
    "ActivitySeverity",
    "ActivitySource",
    "LockEventOrigin",
    "KeypadOperation",
    "Person",
    "PersonData",
    "NotificationEvent",
    "NotificationPreferences",
    "MAX_PROPERTY_NAME_LENGTH",
    "PROPERTY_SETTINGS_SCHEMA_VERSION",
    "PropertySettings",
    "PropertySettingsValidationError",
    "normalize_property_name",
    "NotificationCategory",
    "NotificationDefinition",
    "NOTIFICATION_DEFINITIONS",
    "CATEGORY_TITLES",
    "notification_event_for_activity",
    "LifecycleOperation",
    "LifecycleOperationData",
    "LifecycleOperationStatus",
    "LifecyclePayloadValue",
    "PERMANENT_SCHEDULE_ID",
    "PERMANENT_SCHEDULE_NAME",
    "DayOfWeek",
    "Schedule",
    "ScheduleData",
    "ScheduleEvaluation",
    "SynchronizationStatus",
    "SynchronizationHistoryEvent",
    "SynchronizationHistoryEventData",
    "SynchronizationHistoryEventType",
    "SynchronizationHistorySeverity",
    "aggregate_synchronization_status",
    "WeeklyRule",
    "WeeklyRuleData",
    "authorize_access",
    "activity_event_definition",
    "permanent_schedule",
    "evaluate_schedule",
    "default_keypad_button_actions",
]
